[package]
name = "system"
version = "0.1.0"
edition = "2021"

[dependencies]
futures.workspace = true
gpt = "4.0.0"
thiserror.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
serde_json.workspace = true
serde.workspace = true
superblock.workspace = true
fs-err.workspace = true
